version: '2'

services:
    myapp:
        image: 'bitnami/symfony:1'
        ports:
            - '8003:8000'
            - '33062:3306'
        volumes:
            - '.:/app'
        environment:
            - SYMFONY_PROJECT_NAME=myapp
            - MARIADB_HOST=mariadb
            - MARIADB_PORT_NUMBER=3306
            - MARIADB_USER=bobby
            - MARIADB_PASSWORD=tables
            - MARIADB_DATABASE=myapp
        depends_on:
            - mariadb
        working_dir: /app/myapp
    mariadb:
        image: 'bitnami/mariadb:10.11.2'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=bobby
            - MARIADB_PASSWORD=tables
            - MARIADB_DATABASE=myapp